language: java
sudo: required
env: PHANTOMJS_VERSION="2.1.1"
path: PATH=$PWD/travis-phantomjs:$PATH
jdk:
  - oraclejdk8
  
addons:
  sauce_connect:
    username: "bhadilov"
    access_key: "f319bf71-6e15-4b5d-b421-83441d8ef39f"
    
notifications:
  email:
    on_success: always
    on_failure: never

script: 
- mvn test -B
- bin/phantomjs -v
- phantomjs --webdriver=4444 &

before_script:

-sleep:5
