language: java
sudo: false
jdk:
  - oraclejdk8

before_install:
  - "export PATH=/usr/local/phantomjs-2.1.1/bin:$PATH"
  - "phantomjs --version"

addons:
  sauce_connect:
    username: "bhadilov"
    access_key: "f319bf71-6e15-4b5d-b421-83441d8ef39f"
    
script: mvn test -B
