language: java
sudo: false
jdk:
  - oraclejdk8

before_install:                                                                                                                                                                                                                               
  - wget http://phantomjs.googlecode.com/files/phantomjs-2.1.1-macosx-symbols.tar.bz2                                                                                                                                                             
  - tar -xf phantomjs-2.1.1-macosx-symbols.tar.bz2                                                                                                                                                                                                 
  - sudo rm -rf /usr/local/phantomjs                                                                                                                                                                                                          
  - sudo mv phantomjs-2.1.1-macosx-symbols.tar.bz2 /usr/local/phantomjs

addons:
  sauce_connect:
    username: "bhadilov"
    access_key: "f319bf71-6e15-4b5d-b421-83441d8ef39f"
    
script: mvn test -B
