language: java
sudo: true
jdk:
  - oraclejdk8

before_install: 

  - sudo rm -rf /usr/local/phantomjs
  - curl -L -O https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
  - tar xjf phantomjs-1.9.7-linux-x86_64.tar.bz2
  - sudo mv phantomjs-1.9.7-linux-x86_64 /usr/local/phantomjs

addons:
  sauce_connect:
    username: "bhadilov"
    access_key: "f319bf71-6e15-4b5d-b421-83441d8ef39f"
    
script: mvn test -B
