language: java
sudo: required
jdk:
  - oraclejdk8

addons:
  sauce_connect:
    username: "bhadilov"
    access_key: "f319bf71-6e15-4b5d-b421-83441d8ef39f"
    
notifications:
  email:
    on_success: always
    on_failure: never

before_script:
  -export PATH=$PWD/travis-phantomjs:$PATH

script: mvn test -B
